DROP SEQUENCE BOARDNOSEQ;
DROP SEQUENCE GROUPNOSEQ;
DROP TABLE ANSWERBOARD;

-- 글번호 +1 SEQUENCE
CREATE SEQUENCE BOARDNOSEQ;
-- 그룹번호 +1 SEQUENCE
CREATE SEQUENCE GROUPNOSEQ;

-- 글번호, 그룹번호, 그룹순서, 제목탭, 제목, 내용, 작성자, 작성일
CREATE TABLE ANSWERBOARD(
	BOARDNO NUMBER PRIMARY KEY,
	GROUPNO NUMBER NOT NULL,
	GROUPSQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(1000) NOT NULL,
	REGDATE DATE NOT NULL
);

SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSQ;

INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL, 1, 0, '1번 글', '1번 내용', '유저 1', SYSDATE);

INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL, 1, 0, '2번 글', '2번 내용', '유저 2', SYSDATE);

INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL, 1, 0, '3번 글', '3번 내용', '유저 3', SYSDATE);

INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL, 1, 0, '4번 글', '4번 내용', '유저 4', SYSDATE);

INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL, 1, 0, '5번 글', '5번 내용', '유저 5', SYSDATE);

INSERT INTO ANSWERBOARD
VALUES(
	BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=5),
	(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=5)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=5)+1,
	'RE:5번 글', 'RE:5번 글 내용', '유저 17', SYSDATE
);

UPDATE ANSWERBOARD
SET GROUPSQ = GROUPSQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=5)
AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=5);

INSERT INTO ANSWERBOARD
VALUES(
	BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=5),
	(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=5)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=5)+1,
	'RE:5번 글', 'RE:5번 글 내용', '유저 7', SYSDATE
);

UPDATE ANSWERBOARD
SET GROUPSQ = GROUPSQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=7)
AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=7);

INSERT INTO ANSWERBOARD
VALUES(
	BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=7),
	(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=7)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=7)+1,
	'RE:RE:5번 글', 'RE:RE:5번 글 내용', '유저 8', SYSDATE
);


UPDATE ANSWERBOARD
SET GROUPSQ = GROUPSQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=4)
AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=4);

INSERT INTO ANSWERBOARD
VALUES(
	BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=4),
	(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=4)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=4)+1,
	'RE:4번 글', 'RE:4번 글 내용', '유저 9', SYSDATE
);

UPDATE ANSWERBOARD
SET GROUPSQ = GROUPSQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=9)
AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=9);

INSERT INTO ANSWERBOARD
VALUES(
	BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=9),
	(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=9)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=9)+1,
	'RE:RE:4번 글', 'RE:RE:4번 글 내용', '유저 10', SYSDATE
);

UPDATE ANSWERBOARD
SET GROUPSQ = GROUPSQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=4)
AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=4);

INSERT INTO ANSWERBOARD
VALUES(
	BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=4),
	(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=4)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=4)+1,
	'RE:4번 글', 'RE:4번 글 내용', '유저 11', SYSDATE
);

UPDATE ANSWERBOARD
SET GROUPSQ = GROUPSQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=11)
AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=11);

INSERT INTO ANSWERBOARD
VALUES(
	BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=11),
	(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=11)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=11)+1,
	'RE:RE:4번 글', 'RE:RE:4번 글 내용', '유저 12', SYSDATE
);

SELECT * FROM ANSWERBOARD
ORDER BY GROUPNO DESC, GROUPSQ;
